version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node

  mysql:
    image: mariadb:10.5.9
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-password
      MYSQL_DATABASE: messaging_db
      MYSQL_USER: userA
      MYSQL_PASSWORD: password

  mongodb:
    image: mongo:4.4.4
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: messaging_db